config/routes.rb
LojaVirtual::Application.routes.draw do

  get "blog/index"

  get "blog/search"

  get "blog/show"

  devise_for :users

  get "cart/show"

  namespace :admin do
    root :to => 'welcome#index'
    resources :products
    resources :articles
    resources :sales
    match '/products/category/:category_id' => 'products#index', :as => :products_category
  end
  
  root :to => 'welcome#index'
  match '/user/sales' => 'users#sales'
  match '/category/:category_id' => 'welcome#index', as: :category
  match 'products/category/:category_id' => 'products#index', as: :products_category

  
  resources :products, only: [:show, :index] do
    post   "add_to_cart", on: :member
    put    "change_quantity", on: :member
    delete "remove_from_cart", on: :member
  end 
  
  match 'finish_buy/' => 'finish_buy#index'
  namespace :finish_buy do
  	get 'login'
  	get 'pay'
  end
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :title, :home_headline, :image

  # Uploaders.
  mount_uploader :image, ImageUploader

  # Validation
  validates :image, presence: true
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    
    @article = Article.new(params[:article])
    @article.created_at = Time.now
    if @article.home_headline
      clear_all_headlines
    end

    if @article.save
      respond_to do |format|
        format.html { redirect_to admin_article_path(@article), notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])
    if params[:article][:home_headline]
      clear_all_headlines
    end
    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to admin_article_path(@article), notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to admin_articles_url }
      format.json { head :no_content }
    end
  end

  def clear_all_headlines
    article = Article.find_all_by_home_headline true
    article.each { |a| a.update_attributes home_headline: false if a }
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/views/admin/articles/_form.html.erb
<%= simple_form_for [:admin, @article] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.input :home_headline, as: :radio_buttons %>
  </div>

  <div class="form-image">
    <label> <%= Article.human_attribute_name(:image) %> </label>
    <%= f.file_field :image %> <br />
    <%= image_tag @article.image_url(:thumb), :class => 'img-polaroid' if @article.image? %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_article_path(@article) %> |
<%= link_to 'Back', admin_articles_path %>

app/views/admin/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Image</th>
    <th>Home Headline?</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |admin_article| %>
  <tr>
    <td><%= admin_article.title%></td>
    <td><%= admin_article.body%></td>
    <td><%= image_tag admin_article.image_url(:thumb), :class => 'img-polaroid' if admin_article.image? %></td>
    <td><%= admin_article.home_headline %></td>
    <td><%= link_to 'Show', admin_article_path(admin_article) %></td>
    <td><%= link_to 'Edit', edit_admin_article_path(admin_article) %></td>
    <td><%= link_to 'Destroy', admin_article_path(admin_article), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_admin_article_path %>

app/views/admin/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_articles_path %>

app/views/admin/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p><b><%= @article.title%></b></p>
<p><%= @article.body%></p>
<%= image_tag @article.image_url(:thumb), :class => 'img-polaroid' if @article.image? %>

<%= link_to 'Edit', edit_admin_article_path(@article) %> |
<%= link_to 'Back', admin_articles_path %>