config/routes.rb
LojaVirtual::Application.routes.draw do

  get "blog/index"

  get "blog/search"

  get "blog/show"

  devise_for :users

  get "cart/show"

  namespace :admin do
    root :to => 'welcome#index'
    resources :products
    resources :articles
    resources :sales
    match '/products/category/:category_id' => 'products#index', :as => :products_category
  end
  
  root :to => 'welcome#index'
  match '/user/sales' => 'users#sales'
  match '/category/:category_id' => 'welcome#index', as: :category
  match 'products/category/:category_id' => 'products#index', as: :products_category

  
  resources :products, only: [:show, :index] do
    post   "add_to_cart", on: :member
    put    "change_quantity", on: :member
    delete "remove_from_cart", on: :member
  end 
  
  match 'finish_buy/' => 'finish_buy#index'
  namespace :finish_buy do
  	get 'login'
  	get 'pay'
  end
  

end

app/controllers/admin/welcome_controller.rb
class Admin::WelcomeController < Admin::ApplicationController
  #GET /
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end
end

app/controllers/welcome_controller.rb
require 'product_filter_paginator'
require 'cart_manager'

class WelcomeController < ApplicationController  
  include ProductFilterPaginator
  
  include CartManager
  helper_method :cart
  
  #GET /
  def index   
    # Get headlines
    @home_headlines = Article.find_by_home_headline true
  end
end

app/views/welcome/index.html.erb
<!-- FILTER -->
<div class="filter-form">
  <select id="categories_select" class="categories-select">
    <option class="category-option" 
            selected="selected" 
            data-ajax-href="<%= products_path %>">
      <%= t(:all_categories) %> 
    </option>

    <% @categories.each do |category| %>
      <option class="category-option" 
              data-ajax-href="<%= products_category_path(category) %>"> 
        <%= category.name %> 
      </option>
    <% end %> 
  </select>

  <%= simple_form_for :search, url: search_form_path, method: "GET", html: { id: "search_form", class: "search" } do |f| %>
    <span class="input-append">
      <%= f.text_field :description, :id => "search_field" %>
      <%= f.submit t(:'search.button_text'), :name => nil, 
                          :id => "btn_search", :class => 'btn btn-info' %>
    </span>
  <% end %>
</div>

<!-- PRODUCTS AND PAGINATION -->
<div id="products_and_paginator">
  <%= render partial: "products/index" %>
</div>

<!-- CART -->
<div class="shop-cart clearfix">
  <%= render :partial => "cart/show", locals: { items: @items, products: @cart_products } %>
</div>

app/views/welcome/index.html.haml
.main-highlights
	/ highlights carousel
	#highlights_carousel
		.navigation.left
		.navigation.right

		%ul.pages
			%li
			%li 
			%li 
	/ end highlights carousel

	#static_highlights
		#upper_highlights

		#bottom_highlights

	#shop_highlights
		%p Shop
		%ul
			%li
			%li
			%li
			%li
			%li

	#blog_highlights
		- if !@home_headlines.nil?
			.description
				.area-name Blog
				%h3= @home_headlines.title
				%p= @home_headlines.body

				= link_to 'Saiba mais <span class="arrow-right"></span>'.html_safe ,"#", :class => "know-more"

			.image
				= image_tag @home_headlines.image_url(:thumb) if @home_headlines.image?

		.clear

app/views/welcome/index2.html.erb
<!-- FILTER -->
<div class="filter-form">
  <select id="categories_select" class="categories-select">
    <option class="category-option" 
            selected="selected" 
            data-ajax-href="<%= products_path %>">
      <%= t(:all_categories) %> 
    </option>

    <% @categories.each do |category| %>
      <option class="category-option" 
              data-ajax-href="<%= products_category_path(category) %>"> 
        <%= category.name %> 
      </option>
    <% end %> 
  </select>

  <%= simple_form_for :search, url: search_form_path, method: "GET", html: { id: "search_form", class: "search" } do |f| %>
    <span class="input-append">
      <%= f.text_field :description, :id => "search_field" %>
      <%= f.submit t(:'search.button_text'), :name => nil, 
                          :id => "btn_search", :class => 'btn btn-info' %>
    </span>
  <% end %>
</div>

<!-- PRODUCTS AND PAGINATION -->
<div id="products_and_paginator">
  <%= render partial: "products/index" %>
</div>

<!-- CART -->
<div class="shop-cart clearfix">
  <%= render :partial => "cart/show", locals: { items: @items, products: @cart_products } %>
</div>