config/routes.rb
LojaVirtual::Application.routes.draw do

  get "blog/index"

  get "blog/search"

  get "blog/show"

  devise_for :users

  get "cart/show"

  namespace :admin do
    root :to => 'welcome#index'
    resources :products
    resources :articles
    resources :sales
    match '/products/category/:category_id' => 'products#index', :as => :products_category
  end
  
  root :to => 'welcome#index'
  match '/user/sales' => 'users#sales'
  match '/category/:category_id' => 'welcome#index', as: :category
  match 'products/category/:category_id' => 'products#index', as: :products_category

  
  resources :products, only: [:show, :index] do
    post   "add_to_cart", on: :member
    put    "change_quantity", on: :member
    delete "remove_from_cart", on: :member
  end 
  
  match 'finish_buy/' => 'finish_buy#index'
  namespace :finish_buy do
  	get 'login'
  	get 'pay'
  end
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  # Mass-storage settings.
  attr_accessible :category_id, :code, :description, :price, :image, :category

  # Associations.
  belongs_to :category
  has_many :items
  
  # Uploaders.
  mount_uploader :image, ImageUploader
  
  # Validations.
  validates :code,  uniqueness: true
  validates :code, :description, :price, :category_id, presence: true
  validates :code,  numericality: { only_integer: true, greater_than: 0 }
  validates :code,  length: { maximum: 15 }
  validates :price, numericality: { only_float:   true, greater_than: 0 }
  validates :image, 
    allow_blank: true, 
    format: {
      with: %r{\.(jpe?g)\z}i,
      message: 'must be a JPG'
    }
    
  # Scopes.
  scope :by_category_id, (lambda do |category_id| 
    where category_id: category_id
  end)
  
  scope :by_description, (lambda do |description|
    where "description LIKE ?", "%#{description}%"
  end)

  scope :by_code, (lambda do |code|
    where "code LIKE ?", "%#{code}%"
  end)
  
  def self.search(conditions = {})
  	my_scope = scoped
    my_scope = my_scope.by_category_id conditions[:category_id] if conditions[:category_id]
    my_scope = my_scope.by_description conditions[:search][:description] if conditions[:search] && conditions[:search][:description]
    my_scope = my_scope.by_code conditions[:search][:code] if conditions[:search] && conditions[:search][:code]
    my_scope
  end
end

app/controllers/admin/products_controller.rb
require 'product_filter_paginator'

class Admin::ProductsController < Admin::ApplicationController
  include ProductFilterPaginator

  # GET admin/products
  # GET admin/products.json
  def index
    @categories = Category.all
    @selected_category = params[:category_id]

    # Initialize @products according to user interaction
    filter_products
    paginate_products 15
    
    respond_to do |format|
    	format.html { render "index" }
      if !@products.empty?  
        format.js   { render partial: "index" }
      else
        format.js   { render partial: "products_not_found" }
      end
    end
  end

  # GET admin/products/1
  # GET admin/products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET admin/products/new
  # GET admin/products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET admin/products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST admin/products
  # POST admin/products.json
  def create
    params[:product][:price] = format_float params[:product][:price]
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_path(@product), notice: t(:'products.created') }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT admin/products/1
  # PUT admin/products/1.json

  def update
    params[:product][:price] = format_float params[:product][:price]
    @product = Product.find(params[:id])

    respond_to do |format|
      params[:product][:price] = format_float params[:product][:price]
      if @product.update_attributes(params[:product])
        format.html { redirect_to admin_product_path(@product), notice: t(:'products.edited')  }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE admin/products/1
  # DELETE admin/products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url }
      format.json { head :no_content }
    end
  end
  
  private
  
  def format_float(price)
    price.gsub ",", "."
  end
end

app/controllers/products_controller.rb
require 'product_filter_paginator'
require 'cart_manager'

class ProductsController < ApplicationController
  include ProductFilterPaginator
  
  include CartManager
  helper_method :cart
  
  # GET /products/category/1
  # GET /products/
  def index
    @categories = Category.all
    @selected_category = params[:category_id]
    
    # Initialize @products
    filter_products
    paginate_products 8
    
    # If someone try access from a category link directly,
    # we need load render the cart, and load it.
    load_cart_items if !request.xhr?
    
    respond_to do |format|
    	format.html { render "welcome/index" }
      if !@products.empty?  
        format.js { render partial: "index" }
      else
        format.js { render partial: "products_not_found" }
      end
    end
  end
  
  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end
  
  # POST /products/1/add_to_cart
  # POST /products/1/add_to_cart.js
  # POST /products/1/add_to_cart.json
  def add_to_cart
    @succefully_added = cart.add_item params[:id].to_i
    
    respond_to do |format|
      format.html { redirect_to :root }
      format.js
      format.json { render json: cart }
    end
  end
  
  # DELETE /products/1/add_to_cart
  # DELETE /products/1/add_to_cart.js
  # DELETE /products/1/add_to_cart.json
  def remove_from_cart
    cart.remove_item params[:id].to_i
    
    respond_to do |format|
      format.html { redirect_to :root }
      format.js
      format.json { render json: cart }
    end
  end  
  
  def change_quantity
    cart.change_quantity params[:id].to_i , params[:quantity].to_i
    
    respond_to do |format|
      format.js
      format.html { redirect_to :show }
    end
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  def form_select_categories
    Category.all.map do |c|
      [c.name, c.id]
    end
  end

  def format_product_price
  	exp = Regexp.new Regexp.escape(t 'number.currency.format.unit')  +  "\s*"
    @product.price? ? number_to_currency(@product.price).gsub(exp, "") : ""
  end
end

app/views/admin/products/_form.html.erb
<%= simple_form_for([:admin, @product], :html => {:multipart => true}) do |f| %>
  <%= f.error_notification message: t(:"notice.error.form_contents") %>

  <div class="form-inputs">
    <%= f.input :code, :input_html => { :maxlength => 15 }, :autofocus => true %>
    <%= f.input :description, :as => :text, :input_html => { :rows => 3 } %>     
    <%= f.input :price, :as => :text, 
                               :input_html => { :rows => 1, 
                                                :value => format_product_price,
                                                :class => "currency_field" } %>
    <%= f.input :category_id, collection: form_select_categories, prompt: t(:"products.category.select") %>
  </div>

  <div class="form-image">
    <label> <%= Product.human_attribute_name(:image) %> </label>
	  <%= f.file_field :image %> <br />
    <%= image_tag @product.image_url(:thumb), :class => 'img-polaroid' if @product.image? %>
	</div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
    <%= link_to t(:cancel), admin_products_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/products/_index.html.erb
<% @products.each do |product| %>
  <tr>
    <td><%= product.code %></td>
    <td><%= product.description %></td>
    <td><%= number_to_currency(product.price) %></td>
    <td><%= product.category.name %></td>
    <td>
      <div align="center">  
        <%= link_to ('<i class="icon-share"></i> ').html_safe,
                      admin_product_path(product), :class => 'btn' %> </td>
      </div>
    <td>
      <div align="center">
        <%= link_to ('<i class="icon-edit icon-white"></i> ').html_safe,
                      edit_admin_product_path(product), :class => 'btn btn-info' %> </td>
      </div>
    <td>
      <div align="center">
        <%= link_to ('<i class="icon-remove icon-white"></i> ').html_safe,
                      admin_product_path(product), 
                      method: :delete, 
                      data: { confirm: t(:'notice.are_you_sure') }, 
                      :class => 'btn btn-danger' %>
      </div>
    </td>
  </tr>
<% end %>

app/views/admin/products/_index.js.erb
$("#products").html("<%= j render partial: "admin/products/index.html" %>");

app/views/admin/products/_products_not_found.html.erb
<tr>
	<td colspan="6">
		<h5> <%= t(:'products.not_found') %> </h5>
	</td>
</tr>

app/views/admin/products/_products_not_found.js.erb
$("#products").html(" <%= j render partial: "admin/products/products_not_found.html" %>");

app/views/admin/products/edit.html.erb
<h1> <%= t(:'products.edit') %> </h1>
<%= render 'form' %>

app/views/admin/products/index.html.erb
<div class="header">
  <h1><%= t(:'products.list') %> </h1>

  <div class="form-fields">
    <div class="new-product-btn">
      <%= link_to t(:'products.new'), new_admin_product_path, :class => 'btn' %>
    </div>

    <div class="filter-form">
      <select id="categories_select" class="categories-select">
        <option class="category-option" selected="selected" data-ajax-href="<%= admin_products_path %>">
          <%= t(:all_categories) %> 
        </option>

        <% @categories.each do |category| %>
          <option class="category-option" 
                  data-ajax-href="<%= admin_products_category_path(category) %>"> 
            <%= category.name %> 
          </option>
        <% end %> 
      </select>

      <%= simple_form_for :search, url: admin_products_path, method: "GET", html: { id: "search_form", class: "search" } do |f| %>
        <span class="input-append">
          <%= f.text_field :code, :id => "search_field", placeholder: t('simple_form.placeholders.defaults.code') %>
          <%= f.submit t(:'search.button_text'), :name => nil, :id => "btn_search", :class => 'btn btn-info' %>
        </span>
      <% end %>
    </div>
    <div class="clear"></div>
  </div>

  <div class="clear"></div>
</div>
<div id="admin_products_and_paginator">
<table class="table table-bordered table-hover">
  <thead>
    <th> <%= Product.human_attribute_name(:code) %> </th>
    <th> <%= Product.human_attribute_name(:description) %> </th>
    <th> <%= Product.human_attribute_name(:price) %> </th>
    <th> <%= Product.human_attribute_name(:category) %> </th>
    <th colspan=3></th>
  </thead>
</div>

  <tbody  class="sortable" id="products">
    <%= render :partial => "admin/products/index.html" %>
  </tbody>
</table>
<div id="paginator">
  <%= paginate @products %>
</div>

app/views/admin/products/new.html.erb
<h1> <%= t(:'products.new') %> </h1>
<%= render 'form' %>

app/views/admin/products/show.html.erb
<table class="table table-bordered">
  <thead>
    <th> <%= Product.human_attribute_name(:code) %> </th>
    <th> <%= Product.human_attribute_name(:description) %> </th>
    <th> <%= Product.human_attribute_name(:category) %> </th>
    <th> <%= Product.human_attribute_name(:price) %> </th>
    <th> <%= Product.human_attribute_name(:image) %> </th>
  </thead>
  
  <tbody>
    <tr>
      <td> <%= @product.code %> </td>
      <td> <%= @product.description %> </td>
      <td> <%= @product.category.name %> </td>
      <td> <%= number_to_currency(@product.price) %> </td>
  	  <td> <%= image_tag @product.image_url(:thumb), :class => 'img-polaroid' if @product.image? %> </td>
    </tr>
  </tbody>
</table>

<div class="form-actions">
  <%= link_to t(:edit), edit_admin_product_path(@product), :class => 'btn btn-info' %>
  <%= link_to t(:back), admin_products_path, :class => 'btn' %>
</div>